name: creditum
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: any
  cloud_firestore: any

  google_fonts: any
  font_awesome_flutter: any
  swatcher: any
  floating_bottom_navigation_bar: any
  custom_date_range_picker: any

  auto_size_text: any

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
    - assets/accounts/

